name: build on linux-arm64

on:
  workflow_dispatch:
    inputs:
      perl-versions:
        description: perl versions to build (JSON Array)
        required: false
        default: ""

jobs:
  list:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: set-matrix
        name: list available perl versions
        run: |
          if [ -n "$PERL_VERSIONS" ]; then
            echo "matrix=$(printenv PERL_VERSIONS | jq -c '{perl: .}')" >> "$GITHUB_OUTPUT"
          else
            echo "matrix=$(<versions/perl.json jq -c '{perl: .}')" >> "$GITHUB_OUTPUT"
          fi
        env:
          PERL_VERSIONS: ${{ github.event.inputs.perl-versions }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build:
    runs-on: ubuntu-22.04-arm
    needs:
      - list
    permissions:
      contents: read
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list.outputs.matrix)}}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: build perl
        run: ./build-perl.pl
